Реализация ТЗ проекта №6
pnikishechkin/java-kanban pull request #1
Opened 2024-03-18 10:07 UTC by pnikishechkin

2024-03-18 11:21 UTC, TomattmanYandex requested changes
Привет,  комменты в коде

2024-03-18 11:21 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/history/InMemoryHistoryManager.java
> +    public void linkLast(NodeTask node) {
стоит оставить публичными только методы из интерфейса
чтобы если мы создадим экземпляр не через интерфейс а напрямую через класс, чтобы у нас не было возможности в обход логики выполнять эти действия

2024-03-18 11:21 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/history/InMemoryHistoryManager.java
> +    public NodeTask head;
стоит сделать приватными

2024-03-18 11:21 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/history/InMemoryHistoryManager.java
> +        if (tail != null && tail.data.equals(task)) {
с точки зрения оптимизации может и лучше, с точки зрения логики и понятности, проще было бы просто удалить и добавить заново

Это не надо исправлять просто наблюдение

2024-03-18 11:21 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/history/InMemoryHistoryManager.java
> +        ArrayList<Task> res = new ArrayList<>();
другой способ как это обработать, и он полезен 

ArrayList<Task> res = new ArrayList<>();
NodeTask  node = head;
while(node != null) {
  res.add(node.data);
  node = node.next();
}
return res;

погугли про итераторы

2024-03-18 11:21 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/history/NodeTask.java
> +    public Task data;
модификаторы доступа делаем максимально приватными

ну или можно было сделать приватный вложенный класс и тогда обойтись без этого

2024-03-18 11:21 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/history/InMemoryHistoryManagerTest.java
> +    /*
а почему этот тест закомментирован?
закомментированный код не допускается, удаляем

2024-03-19 09:28 UTC, TomattmanYandex approved these changes
Принято

2024-03-20 05:00 UTC, johnskyi commented on src/main/java/ru/nikishechkin/kanban/manager/history/InMemoryHistoryManager.java
> +    private class NodeTask {
пожалуйста перемести этот класс в самый низ внешнего класса. по код стайлу сперва должны идти переменные поля, потом методы, затем уже внутренние вложенные классы

2024-04-09 12:59 UTC, merged