Реализация ТЗ проекта №7 - хранение задач в файле
pnikishechkin/java-kanban pull request #2
Opened 2024-04-09 16:58 UTC by pnikishechkin

2024-04-10 08:59 UTC, TomattmanYandex requested changes
Комменты в коде

2024-04-10 08:59 UTC, TomattmanYandex commented on resources/defaultTasks.txt
> +id,type,name,status,description,epic
но, есть же тип файлов csv

2024-04-10 08:59 UTC, TomattmanYandex commented on resources/defaultTasks.txt
> +10,SUBTASK,Подзадача 3_3,NEW,Описание,7
а еще почему то в файле нету истории

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/Main.java
> +//        taskManager.addEpic(new Epic("Эпик 1", "Описание")); // ID=0
закомментированный код не допускается

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/Managers.java
> +    // Не совсем понял про применение методов ниже, связанных с сохранением/загрузкой данных по истории просмотра в
1) этим методам точно место не здесь, коменты на эту тему думаю будут в таск менеджере
2) можно без отдельного файла, раньше в условиях было предложено чтобы была пустая строчка, а после нее так же, разделенные запятой,  идентификаторы

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/ManagerLoadException.java
> +package ru.nikishechkin.kanban.manager.task;
ошибки лучше вынести в отдельный пакет

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/ManagerSaveException.java
> +package ru.nikishechkin.kanban.manager.task;
по сути эти две ошибки мало чем будут отличаться, можно оставить одну, и дать чуть более осмысленное имя

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/model/Task.java
> +        return id + "," + type.toString() + "," + name + "," + status.toString() + "," + description;
метод toString предназначен чтобы выводить строковое представление обьекта, и плохой вариант использовать его для трансформации в csv строку 
что бeдет если появится второй возможный формат, ты не сможешь иметь сразу два метода toString

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +                bw.write(task.toString());
Плохой способ это делать
лучше сделать отдельный класс конвертер со статическими методами, которые будут уметь превращать, таски сабтаски, эпики, и список идентификаторов в строку и обратно, и тут его использовать

так во первых будет одно место где определены форматы данных для конкретного типа
во вторых, если появится новый формат, просто делается еще один класс конвертер с такими же методами, и в этих методах заменяется преобразование, а тут заменяется используемый класс

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +
и не хватает истории

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +
и не хватает истории

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void load() {
метод для служебного пользования, должен быть приватным, да и зачем он вообще если просто вызывает другой метод из этого же класса

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void loadFromFile(String fileName) {
кажется по условию этот метод должен быть статическим, и возвращать файловый менеджер
это один из популярных способов создания объектов
делаем приватный конструктор, чтобы нельзя было создать просто так объект класса
и делаем в классе публичный статический метод который возвращает объект этого класса (так как метод часть класса он будет иметь доступ к приватному конструктору

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +        // Files.readString(file.toPath()); - он имеет какие-то преимущества перед BufferedReader?
честно, задача чтения из файлов не самая стандартная, но BuffredReaderя пользовался еще когда начинал, так что это классика, А первый вариант скорее всего посовременнее, но есть большая вероятность, что где то внутри он использует все тот же ридер

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +                Task newTask = getTaskFromString(str);
вот тут стоит сделать хитрую обработку, до пустой строки это обычные объекты, пустая строка, а после него история

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +                    // throw new ManagerLoadException("Ошибка загрузки из файла!");
закомментированный код не допускается
и я бы порекомендовал считать строку в переменную, проверить что она не пустая, и если она не пустая и не история, то уже тогда превращать в таск

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +
не забывай про следующие моменты
1) эпики в файле без сабтасков, а в менеджере должны быть с сабтасками
2) у тебя есть счетчик идентификаторов его тоже надо обновить, чтобы не было пересечения по id  новых тасков с уже существующими

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    private Task getTaskFromString(String str) {
куда подвигать этот метод я писал выше

2024-04-10 08:59 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    }
получение по id тоже надо переопределить ведь они затрагивают историю, а история тоже должна сохраняться

2024-04-12 08:03 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +                bw.write(task.toString());
А если пойти таким путем - сделать вместо метода `toString` у `Task` метод `convertToCsv` и использовать его здесь. Если появится другой формат, использовать другой метод. Такой подход хуже, нежели создавать отдельный класс конвертер?

2024-04-15 16:02 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void load() {
Здесь идея была в том, чтобы сделать метод load, который загружает данные из привязанного файла.
И отдельный метод (больше для тестирования) loadFromFile, который позволяет загрузить данные из стороннего (указанного в параметрах) файла.

2024-04-17 15:36 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void loadFromFile(String fileName) {
> кажется по условию этот метод должен быть статическим, и возвращать файловый менеджер

такого в ТЗ не видел - я сделал реализацию private конструктора в класс Managers, чтобы он использовался только как "создатель" объектов путем вызова статических методов. Насколько я понимаю, такая роль должна быть именно у него.

2024-04-17 15:40 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +
1. Сабтаски добавляются в эпик, поскольку при загрузке из файла я использую метод taskManager.addSubTask для добавления сабтасков, в котором реализована проверка и обновление связанного эпика.
2. Счетчик идентификаторов сбрасывается в методе clearAll, который я вызываю при загрузке задач из файла.

2024-04-18 13:05 UTC, TomattmanYandex requested changes
Привет, добавил еще комментарии
пожалуйста не помечай комментарии как решенные, если ты не исправлял ничего или добавлял к ним свои комментарии (так больше шанс что я их упущу при повторной проверке)

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/Managers.java
> +    public static List<Integer> historyFromString(String str) {
эти методы стоит вынести в отдельный класс конвертер, потому что он к менеджерам отношения не имеет

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/Managers.java
> +    public static List<Integer> historyFromString(String str) {
вижу что есть класс TaskConverterCsv лучше туда

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/history/HistoryManager.java
> +    void clear();
не моему не было такого требования к интерфейсу менеджера истории

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/model/Task.java
> +    public String convertToCsv() {
забыл удалить отсюда и перенести в конвертер

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +            String str = TaskConverterCsv.getStrFromTasksAndHistory(this, historyManager);
было бы гораздо понятнее если бы логика была следующая
в конвертере есть методы, которые преобразуют таски, сабтаски эпики в строку (но одному объекту за раз, а уже тут мы проходим по всем мапам и пишем каждую строку в файл по очереди

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +            String str = TaskConverterCsv.getStrFromTasksAndHistory(this, historyManager);
Сейчас получается что конвертер знает о структуре таск менеджера, а зачем это?

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void load() {
смотри тут есть два варианта логики
но в любом случае этот метод приватный
1) публичный конструктор, который вызывает в себе метод load  + публичный статический метод который возвращает файловый таск менеджер и тоже считывает 
и второй вариант который получше
2) делаем конструктор приватным
статические метод, как часть класса имеет доступ к этому конструктору, и имеет доступ к методу загрузки и он создает объект используя этот приватный конструктор и метод загрузки

В любом случае, при каждом создании объекта мы пытаемся считать данные из привязанного файла
(а в текущей реализации это будет отдельным действием, и следовательно это может не произойти)

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void load() {
по хорошему статический метод loadFormFile должен быть единственным способом создать объект файлового таск менеджера

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +        this.fileName = fileName;
при создании файл должен быть считан

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void loadFromFile(String fileName) {
фрагмент из тз
Кроме метода сохранения, создайте статический метод static FileBackedTaskManager loadFromFile(File file), который будет восстанавливать данные менеджера из файла при запуске программы.

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void loadFromFile(String fileName) {
т.е. этот метод возвращает объект класса FileBackedTaskMAnager уже заполненный данными из указанного файла

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/FileBackedTaskManager.java
> +    public void loadFromFile(String fileName) {
а учитывая что мы должны использовать FileBackedTaskManager через интерфейс, то не получится вызвать эти методы, так как у интерфейса их нету

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +    public void clearAll() {
такого метода в требованиях не было

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +        for (Task task : taskManager.getTasks()) {
вот лучше вариант, чтобы вот это вот было содержимым класса FileBackedTaskManager
1) так он сам будет отвечать за свое наполнение
2) так он будет иметь доступ к вещам к которым нету доступа у внешних файлов
и вот он может вызывать методы из конвертера getCsvFromTask

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +        for (Task task : taskManager.getTasks()) {
getCsvFromTask я бы переименовал в что ни будь в стиле taskToCsvLine

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +        for (Task task : taskManager.getTasks()) {
и перенос на новую строку я бы тоже включил в этот метод, ибо если тут его забудешь добавить то будет проблема

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +        res.append(getIdsStrFromHistory(historyManager));
тут тоже можно было бы переименовать в historyToCsvLine

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +    public static void getTasksAndHistoryFromStr(String str, TaskManager taskManager, HistoryManager historyManager) {
тут то же что и выше, лучше чтобы это было частью таскового менеджера, и н считывал построчно и каждую строку обрабатывал методом из конвертера, потому что с текущей реализацией ты не сможешь реализовать нормально некоторые вещи которые я напишу чуть ниже

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +            if (s.equals(header)) continue;
а зачем это сравнивать, строка хидера всегда одна, просто выполнил в самом начале readLine без записи в переменную и все хорошо, пропустили хидер

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +                        taskManager.addEpic((Epic) newTask);
Методы на добавление заменяют идентификатор, значит их тут использовать нельзя (теряется состояние обьекта, и связи между эпиками и сабтасками

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +                }
после выполнения будут у эпиков пусты списки сабтасков а должны быть заполненые

2024-04-18 13:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +                }
так же после выполнения будет проблема со счетчиком идентификаторов
рекомендация для теста
создай пустой файловый таск менедежер
добавь в него 3 таска
создай новый тасковый менеджер связанный с тем же файлом
в новом тасковом менеджере проверь что есть все таски из первого
добавь в него еще один таск
проверь что
1) количество тасков изменилось, 
2)старые таски остались такими же, 
3) новый добавился

сейчас это скорее всего работать не будет

2024-04-18 13:05 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/task/FileBackedTaskManagerTest.java
> +    void getEpics_checkSize() {
если ты никак не меняешь поведение унаследованного метода, то не наго ничего такого делать, оно выполнится автоматом

2024-04-21 20:47 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +    public void clearAll() {
Да, не было, были только требования по очистке отдельных элементов. Но значит ли это, что добавить такой метод нельзя? Программа должна покрывать все функциональные требования, безусловно, но неужели неправильно добавить какой-либо дополнительный удобный метод?

2024-04-22 11:35 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +            if (s.equals(header)) continue;
Я тут применил метод, который считывает сразу все содержимое файла:
`String str = Files.readString(Paths.get(fileName));`
Соответственно, после этого иду по строкам и смотрю, что за данные в них. Когда встречаю хедер - пропускаю эту строку. Если делать через readLine, то да, можно было бы просто пропустить первую.

2024-04-22 11:41 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +                        taskManager.addEpic((Epic) newTask);
Методы на добавление заменяют идентификатор только в том случае, если его значения нет в объекте задачи:
```
        // Назначение идентификатора
        if (task.getId() == null) {
            task.setId(idCounter);
            idCounter++;
        } else {
            if (tasks.containsKey(task.getId())) {
                System.out.println("Ошибка добавления новой задачи! Задача с таким идентификатором уже существует!");
            }
        }
```
Соответственно, связи между эпиками и сабтасками не теряются - идентификаторы заполняются корректно, и это проверяется в тесте загрузки из файла: `historyInitFromFile`.

2024-04-22 12:40 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +                }
Да, с счетчиком идентификаторов до конца непонятно. Нужно их сбрасывать, или наоборот этого не делать?
Добавил определение счетчика идентификаторов при загрузке файла, по максимальному значению, которое есть в задачах.
```
            // Поиск максимального значения идентификатора задач и его назначение
            idCounter = Math.max(Math.max(Collections.max(epics.keySet()), Collections.max(subTasks.keySet())),
                     Collections.max(tasks.keySet())) + 1;
```

Тест сделал, вроде добавляет корректно: `createTwoFileManagers`

2024-04-22 14:00 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +    public void clearAll() {
иногда требования надо соблюдать, и такого делать нельзя, но не в этом случае, главное чтобы было понимание, как должны взаимодействовать кмопоненты (например если бы был метод на получение мап, то такой тоже мог бы быть, но там уже проблема в безопасности

2024-04-22 14:01 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/TaskConverterCsv.java
> +            if (s.equals(header)) continue;
ну тут тоже можно было просто пропустить первый элемент списка

2024-04-22 14:02 UTC, TomattmanYandex approved these changes
Привет, принято

2024-04-23 09:56 UTC, merged