Реализация проекта №8.
pnikishechkin/java-kanban pull request #3
Opened 2024-05-08 06:55 UTC by pnikishechkin

2024-05-08 10:02 UTC, TomattmanYandex requested changes
Привет, вроде как по большей части все хорошо
есть коменты на улучшение, плюс пара моментов на исправление, проверь, что при очищении какого то конкретного типа, все удаляются из приоритезированных тасок
ПО тестам тоже есть вопросы, часть из них как будто не на своих местах, часть из них непонятно что тестируют, часть из них с потерянной структурой, и поэтому тоже непонятно что тестируют
Напомню по хорошему имени метода должно быть все понятно
например 
addTask_addTaskToPrioritizedList_taskContainsStartTime
addTask_notAddTaskToPrioritizedList_taskNotContainsStartTime 
и по хорошему такие методы должны быть на таск, на сабтаск, должен быть метод типа
addEpic_notAddEpicToPrioritizedList
И такие же методы на обновление
Плюс  хорошей опцией было бы делать тесты на все ошибки что были замечены в результате проверки
например
clearTasks_deleteTasksFromPrioritizedList
и такие же на очищение сабтасков и эпиков

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/model/Task.java
> +        if (o.startTime.isPresent() && this.startTime.isPresent()) {
эта реализация будет работать не правильно, ибо не обрабатываются случаи, когда хоть один из них null , таких случаев три и каждый будет иметь разный результат
второй момент, лучше создать отдельный класс компаратор и использовать его (так мы отделим модель от логики)

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        });
когда мы очистим сабтаски, список prioritizedTasks не очистится

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/model/Task.java
> +        if (o.startTime.isPresent() && this.startTime.isPresent()) {
на первый пункт не обращай внимания, раньше в задаче было указано что в начале будет таски по времени старта, а в конце списка без времени старта, теперь этот момент убрали

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +            prioritizedTasks.remove(task);
а зачем мы удаляем, мы же его еще не добавили(

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        // Проверка на пересечение с другими задачами
этот код дублируется, почему бы его не вынести в отдельный метод, а для того чтобы выполнение шло дальше или нет, можно пробрасывать исключения в методе, а тут его отлавливать

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        // Проверка на пересечение с другими задачами
про дублирование кода писал выше

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        if (prioritizedTasks.stream().filter(t -> checkTasksOverlap(subTask, t)).findAny().isPresent()) {
дублирование кода

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        if (oldSubTask != null) {
хороший вариант, чтобы избежать проверки на самого себя, или при проверке пересечений можно было бы проверять что эо не один и тот же таск

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        if (prioritizedTasks.stream().filter(t -> checkTasksOverlap(task, t)).findAny().isPresent()) {
дублирование кода

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        Task oldTask = getTaskById(task.getId());
кажется эта логика тоже дублируется, кажется проще было бы, вместо этого при проверке на пересечение, проверять что это не тот же таск и все

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        Epic epic = this.epics.get(epicId);
метод выглядит сложновато
как упростить и улучшить
1) зачем итерироваться по списку идентификаторов и потом получать по нему сабтаски, если есть метод который возвращает список сабтасков эпика, и можно итерироваться сразу по ним
2) если изменить компаратор, так, чтобы он обрабатывал и null занчения startTime то:
создаем сортированый список, с этими сабтасками и первый элемент в нем, будет иметь время старта равное с временем старта эпика, а последний будет иметь время финиша равное времени финиша эпика, ну и сумма это продолжительность
С текущей реализацией сравнения надо будет вначале отфильтровать те которые без времени старта

2024-05-08 10:02 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +    private boolean checkTasksOverlap(Task task1, Task task2) {
сложновато, но вроде норм, единственное что бы я предложил сделать, это первым действием сделать проверку идентификатора
if(task1.getId().equals(task2.getId()) {
return false;
} и тогда можно будет при обновлении, не удалять из списка приоритезированных тасков

2024-05-08 10:02 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void initTasks_checkDates() {
какой метод тут тестируется?

2024-05-08 10:02 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void changeTasks_checkDates() {
и тут не понятно что тестируется, но судя по коду, тестируются сеттеры и геттеры?
не уверен что такой тест имеет смысл
точнее имеет смысл часть с проверкой времени окончания, но это логика теста модели

2024-05-08 10:02 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void initEpics_checkDates() {
аналогично

2024-05-08 10:02 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void changeEpics_checkDates() {
вот тут уже логика на наужном месте, так как эпики зависят от сабтасков

2024-05-08 10:02 UTC, TomattmanYandex commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void initAndChangeTasks_checkPrioritizedTasksList() {
и снова не понятно какой метод тестируется
плюс стуктура теста потерялась

2024-05-11 19:43 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/model/Task.java
> +        if (o.startTime.isPresent() && this.startTime.isPresent()) {
Создал отдельный класс TaskComparator. Только вопрос, где его правильнее разместить? Сейчас реализовал прямо в InMemoryTaskManager, поскольку он и используется только в нем.

2024-05-11 20:19 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +            prioritizedTasks.remove(task);
Идея в том, что этот метод вызывается всякий раз, когда обновляется задача. И если обновили данные задачи, у которой ранее был задан startTime, а в новом объекте таски он не задан (null), тогда бы удаляем этот объект из списка отсортированных тасок

2024-05-11 20:20 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +            prioritizedTasks.remove(task);
У метода было название, не совсем точно отражающее его поведение, переименовал.

2024-05-11 20:46 UTC, pnikishechkin commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void initAndChangeTasks_checkPrioritizedTasksList() {
"Структура теста потерялась" - имеется ввиду, что идет init, затем then, затем when, then ?
Насколько это некорректно? Обязательно должен быть только одна группа событий init, when, then в одном тесте?

2024-05-12 10:19 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        if (oldSubTask != null) {
Добавил в проверке пересечений

2024-05-12 10:23 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        Task oldTask = getTaskById(task.getId());
Не совсем понял, на какой участок кода указываете. В проверке на пересечение добавлена логика проверки на ту же задачу.

2024-05-12 20:40 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        Epic epic = this.epics.get(epicId);
1. Есть, теперь используется имеющийся метод
2. А как компаратору обрабатывать null значения? Считать, что такие объекты меньше тех, у которых значения есть? Сделал с предварительной фильтрацией объектов, у которых startTime не null

2024-05-12 21:16 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +    private boolean checkTasksOverlap(Task task1, Task task2) {
Проверку на равенство идентификаторов сделал.
Но удалять старый объект все равно же нужно, ведь в новом объекте дата могла поменяться?

2024-05-12 21:17 UTC, pnikishechkin commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void initTasks_checkDates() {
Метод, связанный с назначением дат для эпика на основе данных его сабтасков.
Этот: updateEpicTimes

2024-05-12 21:21 UTC, pnikishechkin commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void initEpics_checkDates() {
Описал смысл данного теста выше

2024-05-12 21:22 UTC, pnikishechkin commented on test/ru/nikishechkin/kanban/manager/task/TaskManagerTest.java
> +    void changeTasks_checkDates() {
Да, здесь скорее есть смысл только endTime тестировать, оставил только его.
Перенес в тест модели.

2024-05-12 21:25 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +        });
Исправил, добавил тест для проверки данной ситуации

2024-05-13 07:24 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/manager/task/InMemoryTaskManager.java
> +    Comparator<Task> taskComparatorByDate = new Comparator<>() {
тут бы тоже модификатор доступа

2024-05-13 07:24 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/model/Task.java
> +        if (o.startTime.isPresent() && this.startTime.isPresent()) {
нормально, я предпочитаю выносить все в отдельный классы, но если используется только в одном месте, то почему бы и нет

2024-05-13 07:25 UTC, TomattmanYandex approved these changes
Принято

2024-05-13 07:41 UTC, merged