Реализация проекта №9
pnikishechkin/java-kanban pull request #4
Opened 2024-05-27 10:33 UTC by pnikishechkin

2024-05-27 12:10 UTC, TomattmanYandex requested changes
Привет, вроде все хорошо, но можно поулучшать немного читабельность кода

2024-05-27 12:10 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/server/BaseHttpHandler.java
> +package ru.nikishechkin.kanban.server;
как тут много классов разных по функционалу и все в одном пакете, было бы хорошо разбить на подпакеты

2024-05-27 12:10 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
один длиннющий метод,в котором тяжело разобраться, можно было бы разбить его на методы поменьше
например, сначала выяснили тип запроса
если Get то вызвали метод который обрабатывает только get запросы 
потом проверили еще какие то условия и вызвали новый метод
несколько маленьких методов с хорошими именами гораздо лучше чем один огромный

2024-05-27 12:10 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
у тасков и сабтасков можно так же улучшить

2024-05-28 09:05 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/server/BaseHttpHandler.java
> +package ru.nikishechkin.kanban.server;
Раскидал по пакетам

2024-05-28 09:08 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
Раскидал по разным методам.
- В классах EpicHandler и TaskHandler разбил в зависимости от HTTP метода: GET, POST и DELETE. Получилось больше кода, но логически код наверное понятнее.
- В SubtaskHandler разбил в зависимости от пути: /subtask или /subtask/{id}  Здесь получилось меньше кода, но возможно код чуть запутаннее.

Как на твой взгляд, как сделать лучше?

2024-05-28 09:09 UTC, pnikishechkin commented
Подскажи еще, насколько критичен следующий warning, который формируется при старте сервера?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.ReflectionHelper (file:/D:/Dev/JavaPraktikum/dev/java-kanban/lib/gson-2.9.0.jar) to constructor java.util.Optional()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.ReflectionHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

2024-05-28 09:12 UTC, pnikishechkin commented
Подскажи еще, как избежать NullPointerException в EpicHandlerTest? Если не задать указанные параметры:

```
    @Test
    public void addNewEpic_EpicAdded() {

        Epic newEpic = new Epic("Эпик НОВЫЙ", "Описание");

        ////////////////////////////////////////////////////////////////////////////////////////////////////
        // Если не задать данные параметры, то при конвертации объекта в Json вылетает NullPointerException
        // Как этого избежать?
        newEpic.setStartTime(LocalDateTime.of(2050, 01, 02, 20, 30));
        newEpic.setEndTime(LocalDateTime.of(2050, 01, 02, 20, 40));
        newEpic.setDuration(Duration.ofMinutes(10));
        newEpic.setStatus(TaskStatus.NEW);
        ////////////////////////////////////////////////////////////////////////////////////////////////////
```

2024-05-28 15:05 UTC, TomattmanYandex commented on src/main/java/ru/nikishechkin/kanban/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
Как по мне лучше больше кода, но чтобы было понятнее

2024-05-28 15:09 UTC, TomattmanYandex reviewed
сразу отвечу на вопросы про тесты
скорее всего ошибка падает в адаптерах, потому что они не берут в расчет то, что там может быть null
делаешь в них проверку на null и в случае если null выводишь либо сам null Либо пустую строку и все должно заработать,
но в следующий раз лучше кидай так же саму ошибку, ибо без текста не очень понятно что и как

Отправляю на переделку чтобы пофиксал это, если совет выше не поможет, пиши в сообщения перед сдачей, подумаем

2024-05-29 09:11 UTC, pnikishechkin commented on src/main/java/ru/nikishechkin/kanban/server/EpicHandler.java
> +    public void handle(HttpExchange exchange) throws IOException {
Согласен, исправил

2024-05-29 09:20 UTC, pnikishechkin commented
Все исправил, проверки на null помогли.

2024-05-30 07:42 UTC, TomattmanYandex approved these changes
Принято

2024-05-30 14:03 UTC, merged